version: '3'
services:
  db:
    image: postgres
    container_name: myapp_container
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: dbpass
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    healthcheck:
      test: |
        apk add --no-cache sqlite
        sqlite3 /var/lib/pgadmin/pgadmin4.db 'INSERT OR IGNORE INTO server (id, user_id, servergroup_id, name, host, port, maintenance_db, username, password, ssl_mode, use_ssh_tunnel, tunnel_port, tunnel_authentication, connect_timeout) VALUES (10, 1, 1, "postgres_my_local", "my_container", 5432, "my_db", "my_user", "dbpass", "prefer", 0, 22, 0, 0);' '.exit'
        exit 1
      interval: 0s
      timeout: 10s
      retries: 1
    links:
      - db
    depends_on:
      - db
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@greenlife.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped